version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up --build -d
          command: docker-compose build
      - run:
          name: sleep for waiting launch db
          command: sleep 10
      - run:
          name: rails db:create & db:migrate
          command: docker-compose run web rails db:create db:migrate
      # - run:
      #     name: rails db:create
      #     command: docker-compose exec --env 'RAILS_ENV=test' web rails db:create
      # - run:
      #     name: rails db:migrate
      #     command: docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
      - run:
          name: test #将来的にはrspec
          command: docker-compose exec --env 'RAILS_ENV=test' web bundle exec test
      - run:
          name: docker-compose down
          command: docker-compose down
